---
name: Create release PR

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        run: |
          git clone --branch release "${REPO_URL}"
          cd renovate-config
          git fetch origin main
          git switch -c main --track origin/main

          set -x
          if [[ $(git merge-base main release) == $(git rev-parse main) ]]; then
              echo "No changes found in main, skip PR creation"
              exit 0
          fi

          PR=$(gh pr create --title "Release week $(date +%V)" --body "Automatically created PR to merge main into release" --base release --head main)
          RETVAL=$?
          if [ "${RETVAL}" -ne 0 ]; then
              echo "Error while creating pull request, error: ${PR}" >> $GITHUB_STEP_SUMMARY
          else
              echo "Created pull request: ${PR}" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
