---
name: Create release PR

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Create PR
        run: |
          PR=$(gh pr create --title "Release week $(date +%V)" --body "Automatically created PR to merge main into release" --base release --head main)
          RETVAL=$?
          if [ "${RETVAL}" -ne 0 ]; then
              echo "Error while creating pull request, error: ${PR}" >> $GITHUB_STEP_SUMMARY
          else
              echo "Created pull request: ${PR}" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
