---
name: Run renovate-config-validator

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Validate config 
        run: |
          docker run --entrypoint=renovate-config-validator --volume "$(pwd):/tmp" renovate/renovate:slim /tmp/default.json
