name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - run: make validate

  call-workflow:
    permissions:
      contents: read
      id-token: write

    uses: ./.github/workflows/renovate-vault.yml
    with:
      configMigration: 'true'
      logLevel: 'debug'
      overrideSchedule: "{'schedule':null}'"
      renovateConfig: ${{ inputs.renovateConfig || '.github/renovate.json' }}
      dryRun: 'full'
